# LAB-2-b
### Analysis of TfIdf Vectorizer

- [Corpus Of Words](#Corpus-of-Words)
- [TfIdf Vectorizer](#TfIdf-Vectorizer)
- [Cosine Similarity](#Cosine-Similarity)

### Analysis of n-gram 

- [Implement Bigram](#Implement-Bigram)

### Author

- [Navaneeth Sivakumar - 21BAI1302](https://github.com/Sivakumar-Navaneeth)

### Analysis of TfIdf Vectorizer

#### Corpus of Words

In [1]:
import pandas as pd

corpus = pd.read_csv("Dataset\my_data.csv")
corpus.head(5)

C:\Users\navan\AppData\Local\Temp\ipykernel_12092\2880933031.py:1: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


Sentences
0  The sun is the largest celestial body in the s...
1  The solar system consists of the sun and eight...
2                       Ra was the eygyptian sun god
3  The pyramids were the pinacle of Egyptian arch...
4        The quick brown fox jumps over the lazy dog

In [2]:
corpus = corpus["Sentences"].values
print(type(corpus),corpus,sep="\n\n")

<class 'numpy.ndarray'>

['The sun is the largest celestial body in the solar system'
 'The solar system consists of the sun and eight revolving planets'
 'Ra was the eygyptian sun god'
 'The pyramids were the pinacle of Egyptian architecture'
 'The quick brown fox jumps over the lazy dog']


#### TfIdf Vectorizer

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
vect = tfidf.fit_transform(corpus)

#### Cosine Similarity

In [4]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity = cosine_similarity(vect,vect)
print(cosine_similarity)

[[1.         0.36413198 0.17617752 0.17937973 0.16336438]
 [0.36413198 1.         0.14481197 0.21119119 0.11203887]
 [0.17617752 0.14481197 1.         0.08200203 0.07468074]
 [0.17937973 0.21119119 0.08200203 1.         0.126105  ]
 [0.16336438 0.11203887 0.07468074 0.126105   1.        ]]


### Analysis of n-gram 

#### Implement Bigram

In [5]:
import nltk
# nltk.download('punkt')
from nltk.util import ngrams

sentence1 = "The sun is the largest celestial body in the solar system"
ngram_pairs = ngrams(sequence=nltk.word_tokenize(sentence1), n=2)
for pairs in ngram_pairs:
    print(pairs)


('The', 'sun')
('sun', 'is')
('is', 'the')
('the', 'largest')
('largest', 'celestial')
('celestial', 'body')
('body', 'in')
('in', 'the')
('the', 'solar')
('solar', 'system')
